DELETE FROM SUPERVISOR;
DELETE FROM DEPARTMENTS;
DELETE FROM COMPUTERS;
DELETE FROM EMPLOYEES_ID;
DELETE FROM TRAINING_PROGRAMS;
DELETE FROM PAYMENT_TYPES;
DELETE FROM CUSTOMERS;
DELETE FROM ORDERS;
DELETE FROM PRODUCTS;
DELETE FROM PRODUCT_TYPES;


DROP TABLE IF EXISTS  EMPLOYEES_ID ;
DROP TABLE IF EXISTS  COMPUTERS;
DROP TABLE IF EXISTS  TRAINING_PROGRAMS;
DROP TABLE IF EXISTS  PAYMENT_TYPES;
DROP TABLE IF EXISTS  DEPARTMENTS;
DROP TABLE IF EXISTS  PRODUCTS;
DROP TABLE IF EXISTS  PRODUCT_TYPES;
DROP TABLE IF EXISTS  ORDERS;
DROP TABLE IF EXISTS  SUPERVISOR;
DROP TABLE IF EXISTS  CUSTOMERS;




CREATE TABLE `EMPLOYEE_ID` (
	`EMPLOYEES_ID`  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`NAME`  TEXT NOT NULL,
	`Gender` TEXT NOT NULL,
	`Profession` TEXT NOT NULL,
	`SuperheroId` INTEGER NOT NULL,
	FOREIGN KEY(`SuperheroId`) REFERENCES `Superhero`(`SuperheroID`)
);

CREATE TABLE `COMPUTERS`

CREATE TABLE `EMPLOYEES_ID` (
  `EMPLOYEES_ID` INT NOT NULL,
  `Department_ID` VARCHAR(45) NULL,
  `Training_ProgramID` VARCHAR(45) NULL,
  `Computer_ID` VARCHAR(45) NULL,
  `Supervisor_ID` INT NULL,
  `Supervisor_Name` VARCHAR(45) NULL,
  `Employee_Name` VARCHAR(45) NULL,
  PRIMARY KEY (`EMPLOYEES_ID`),
  CONSTRAINT `Department_ID`
    FOREIGN KEY ()
    REFERENCES `DEPARTMENTS` ()
   
   


CREATE TABLE `SUPERVISOR` (
  `SUPERVISOR_ID` INT NOT NULL,
  `EMPLOYEES_ID` INT NULL,
  PRIMARY KEY (`SUPERVISOR_ID`))

 CREATE TABLE `TRAINING_PROGRAMS` (
  `TRAINING_PROGRAM_ID` VARCHAR(45) NULL,
  `Employees_ID` INT NOT NULL,
  `Employee_Name` VARCHAR(45) NULL,
  `Program_Start` DATE NULL,
  `Program_End ` DATE NULL,
  `Maximum_Slots` INT NULL,
  PRIMARY KEY (`Training_ProgramID)


  )

CREATE TABLE `COMPUTERS_has_EMPLOYEES_ID` (
  `COMPUTERS_Computer_ID` INT NOT NULL,
  `EMPLOYEES_ID_EMPLOYEES_ID` INT NOT NULL,
  PRIMARY KEY (`COMPUTERS_Computer_ID`, `EMPLOYEES_ID_EMPLOYEES_ID`),
  INDEX `fk_COMPUTERS_has_EMPLOYEES_ID_EMPLOYEES_ID1_idx` (`EMPLOYEES_ID_EMPLOYEES_ID` ASC),
  INDEX `fk_COMPUTERS_has_EMPLOYEES_ID_COMPUTERS1_idx` (`COMPUTERS_Computer_ID` ASC),
  CONSTRAINT `fk_COMPUTERS_has_EMPLOYEES_ID_COMPUTERS1`
    FOREIGN KEY (`COMPUTERS_Computer_ID`)
    REFERENCES `mydb`.`COMPUTERS` (`Computer_ID`)
  CONSTRAINT `fk_COMPUTERS_has_EMPLOYEES_ID_EMPLOYEES_ID1`
    FOREIGN KEY (`EMPLOYEES_ID_EMPLOYEES_ID`)
    REFERENCES `mydb`.`EMPLOYEES_ID` (`EMPLOYEES_ID`)
  



CREATE TABLE `EMPLOYEES_ID_has_TRAINING_PROGRAMS` (
  `EMPLOYEES_ID_EMPLOYEES_ID` INT NOT NULL,
  `TRAINING_PROGRAMS_Training_ProgramID` INT NOT NULL,
  PRIMARY KEY (`EMPLOYEES_ID_EMPLOYEES_ID`, `TRAINING_PROGRAMS_Training_ProgramID`),
  INDEX `fk_EMPLOYEES_ID_EMPLOYEES_ID) 


